#!/usr/bin/env bash

set -e

BASE_CONFIG="defaults"
CONFIG_SUFFIX=".yaml"

META_DIR="deploy"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


cd "${BASE_DIR}"
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule update --init --recursive "${META_DIR}/${DOTBOT_DIR}"
GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule update --init --recursive "${META_DIR}/dotbot-brew"


while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "${META_DIR}/${PROFILES_DIR}/$1${CONFIG_SUFFIX}"

shift


"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir ${BASE_DIR}/${META_DIR}/dotbot-brew -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

for config in ${CONFIGS} ${@}; do
    echo -e "\nConfigure $config"
    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir ${BASE_DIR}/${META_DIR}/dotbot-brew -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
done
