#!/usr/bin/env bash

set -e

BASE_CONFIG="defaults"
CONFIG_SUFFIX=".yaml"

META_DIR="deploy"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
DOTBOT_PLUGIN_DIR="dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


cd "${BASE_DIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"


"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir ${BASE_DIR}/${META_DIR}/dotbot-brew -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

for config in ${@}; do
    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir ${BASE_DIR}/${META_DIR}/dotbot-brew -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
done
