" ============================================
" Vim configuration
" ============================================

" ================ Leader ====================
let mapleader = ','
let maplocalleader = ','
set nocompatible        " must be first line

" ======= Windows compatibility ==============
" On Windows, also use '.vim' instead of 'vimfiles'; this makes synchronization
" across (heterogeneous) systems easier.
if has('win32') || has('win64')
  set runtimepath=$HOME/.vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$HOME/.vim/after
endif

" =============== Vundle Initialization ===============
" This loads all the plugins specified in ~/.vim/vundles.vim
" Use Vundle plugin to manage all other plugins
if filereadable(expand("~/.vim/vundles.vim"))
    source ~/.vim/vundles.vim
endif
" This loads the settings of the bundles
source ~/.vim/settings.vim

" Use local vimrc if available {
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif

" =============== Basic settings ===============
filetype plugin indent on   " Automatically detect file types.
syntax on                   " syntax highlighting
set mouse=a                 " automatically enable mouse usage

" Encoding
scriptencoding utf-8
set encoding=utf-8   " Show unicode glyphs

" Misc
set esckeys          " Allow cursor keys in insert mode
set viewoptions=folds,options,cursor,unix,slash " better unix / windows compatibility
set history=100                 " Store a ton of history (default is 20)
set ttyfast                     " Optimize for fast terminal connections
set binary           " Don't add empty newlines at end of files
set noeol            " Don't add empty newlines at end of files
set noerrorbells     " Disable error bells
set visualbell
set t_vb=
set tm=500

" Set backup, undo, swap
set nobackup
set nowb
set noswapfile

" =============== Status line ===============
set shortmess+=filmnrxoOtT      " abbrev. of messages (avoids 'hit enter')
if has('statusline')
    set laststatus=2
endif

" =============== Some extra behavior ===============
set backspace=indent,eol,start  " backspace for dummies
set linespace=0                 " No extra spaces between rows
set showmatch                   " show matching brackets/parenthesis
set shm=AI
set winminheight=0              " windows can be 0 line high
set nolist
set listchars=tab:,.,trail:.,extends:#,nbsp:. " Highlight problematic whitespace
set lcs=tab:▸\ ,trail:·,eol:¬,nbsp:_

" =============== Formatting ===============
set autoindent                  " indent at the same level of the previous line
set shiftwidth=4                " use indents of 4 spaces
set tabstop=4                   " an indentation every four columns
set softtabstop=4               " let backspace delete indent

" Install from GitHub
let $GIT_SSL_NO_VERIFY = 'true'

" Set expandtab in the end
set expandtab

" EOF
