- brew:
    - zsh
    - git
    - python
#    - python@2
    - ssh-copy-id
    - coreutils
    - readline
    - gettext
    - lua
    - gnupg

- tap:
#    - caskroom/versions
    - homebrew/cask-fonts
    #- buo/cask-upgrade
