- link:
    ~/.paths: machine/mac/paths
    ~/.aliases: machine/mac/aliases
    ~/.localrc: machine/mac/localrc
    ~/.ripgreprc: machine/mac/ripgreprc

# Formulae
- brew:
    - automake
    - autoconf
    - llvm
    - gcc
    - cmake
    - glib
    - vala
    - ctags
    - git-extras
    - hub
    - wget
    - rsync
    - curl
    - ruby
    - pkg-config
    - boost
    - berkeley-db
    - sqlite
    - openssl
    - fontforge
    - freetype
    - fontconfig
    - lcdf-typetools
    - parallel
    - fftw
    - git-annex
    - git-lfs
    - gsl
    - isl
    - gpg2
    - gnuplot
    - iftop
    - tmux
    - reattach-to-user-namespace
    - gd
    - flac
    - lame
    - exiftool
    - ghostscript
    - x264
    - libmatroska
    - pygobject
    - mobile-shell
    - pandoc
    - pandoc-citeproc
    - cloc
    - graphviz
    - mackup
    - svn
    - fpp
    - python3
    - burntsushi/ripgrep/ripgrep-bin
    - qt
    - mas
    - peco
    - bib-tool
    - youtube-dl

# Software
- cask:
    - adapter
    - android-platform-tools
    - bibdesk
    - calibre
    - cyberduck
    - day-o
    - dropbox
    - evernote
    - franz
    - gimp
    - google-chrome
    - iterm2-beta
    - latexit
    - libreoffice
    - mactex
    - mathpix-snipping-tool
    - mkvtoolnix
    - nvalt
    - scummvm
    - skype
    - soulseek
    - spectacle
    - spotify
    - the-unarchiver
    - transmission
    - xquartz
    - vlc

# Apple store
#- shell:
#    - command: mas signin --dialog "djkarras@gmail.com"
#      stdout: true
#      stderr: true
#      stdin: true
    # mas list
#937984704 Amphetamine (4.2)
#409201541 Pages (8.0)
#409183694 Keynote (9.0.2)
#408981434 iMovie (10.1.12)
#404010395 TextWrangler (5.5.2)
#409203825 Numbers (6.0)
#    - [mas install 937984704 409201541 409183694 408981434 404010395 409203825, Installing apps from the App Store]

- shell:
    - ["open https://member.ipmu.jp/yuji.tachikawa/MenuMetersElCapitan/", Install MenuMeters!]

# Fonts
- cask:
    - font-source-code-pro-for-powerline
    - font-inconsolata-dz-for-powerline
    - font-inconsolata
    - font-source-code-pro
    - font-source-sans-pro
    - font-source-serif-pro
    - font-raleway
    - font-raleway-dots
    - font-fjalla-one
    - font-alfa-slab-one
    - font-montserrat
    - font-montserrat-subrayada
    - font-antic-slab
    - font-crimson-text
    - font-domine
    - font-bitter
    - font-open-sans
    - font-open-sans-condensed
    - font-fira-mono
    - font-fira-mono-for-powerline
    - font-fira-sans
    - font-lato
    - font-tex-gyre-pagella
    - font-tex-gyre-pagella-math
    - font-alegreya
    - font-alegreya-sans
      #- font-alegreya-sans-sc
      #- font-alegreya-sc
    - font-fontawesome
    - font-awesome-terminal-fonts
    - font-academicons
    - font-public-sans

# Fix a few things
- shell:
    - description: "Configuring defaults"
      command: "machine/mac/defaults.sh"  # Set zsh as default shell
      stdout: true
      stderr: true
      stdin: true
    - description: "Fixing zsh"
      command: "machine/mac/fix_zsh.sh"
      stdout: true
      stderr: true
      stdin: true
