# Setup what is needed, create folders, etc
- clean: ['~']

- shell:
    - [mkdir -p $HOME/.local, Make local dir]
    - [mkdir -p $HOME/.config, Make local config dir]

- shell:
    - [GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule update --init --recursive, Pulling submodules]

