# Zsh
- shell
  - [curl -fsSL https://raw.githubusercontent.com/zimfw/install/master/install.zsh | zsh, Installing zim]
  - [zimfw install, Installing zim modules]


# Config files
- link:
    ~/.zlogin: zsh/zlogin
    ~/.zlogout: zsh/zlogout
    ~/.zprofile: zsh/zprofile
    ~/.zshrc: zsh/zshrc
    ~/.zimrc: zsh/zimrc
    ~/.zshenv: zsh/zshenv
    ~/.purepower: zsh/gimbo.zsh
