# Zsh
# Prezto is a submodule
- shell:
    - [git submodule update --init --recursive prezto, Deploying/updating prezto]

# Make sure it's linked properly
- link:
    ~/.zprezto: prezto

# Config files
- link:
    ~/.zlogin: zsh/zlogin
    ~/.zlogout: zsh/zlogout
    ~/.zpreztorc: zsh/zpreztorc
    ~/.zprofile: zsh/zprofile
    ~/.zshrc: zsh/zshrc
    ~/.zshenv: zsh/zshenv
    ~/.zprezto/modules/prompt/functions/prompt_apuignav_setup: zsh/prompt/prompt_apuignav_setup
