# Your previous .profile  (if any) is saved as .profile.dpsaved
# Setting the path for DarwinPorts.
  . $HOME/.mybash

# DIRAC prompt
  if [ "$DIRACROOT" ]; then
    export PS1='\[\033[01;31m\](DIRAC) \u@\h\[\033[00m\]:\[\033[00;36m\]\w\[\033[00m\]\$ '
  fi

# Environment variables
  export EDITOR="vim"
  export GIT_EDITOR="vim"
  export UNISONLOCALHOSTNAME=dc10
  export OS=Darwin
  export MANPATH=$MANPATH:$BREW/man
  export ANDROID_SDK_ROOT=$HOME/android

# Bash completion
  # LD_LIBRARY_PATH
  NEW_LD_LIBRARY_PATH=$ROOTSYS/lib:$BREW/lib:/usr/lib
  if [ -z "$LD_LIBRARY_PATH}" ]; then
    LD_LIBRARY_PATH=$NEW_LD_LIBRARY_PATH; export LD_LIBRARY_PATH
  else
    LD_LIBRARY_PATH=$NEW_LD_LIBRARY_PATH:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
  fi
  # PATH
  NEW_PATH=$HOME/git/gitolite/src/
  if [ -z "${PATH}" ]; then
    PATH=$NEW_PATH; export PATH
  else
    PATH=$NEW_PATH:$PATH; export PATH
  fi
  # PYTHONPATH
  NEW_PYTHONPATH=$HOME/python:$HOME/packages/lib/python
  if [ -z "${PYTHONPATH}" ]; then
    PYTHONPATH=$NEW_PYTHONPATH; export PYTHONPATH
  else
    PYTHONPATH=$PYTHONPATH:$NEW_PYTHONPATH; export PYTHONPATH
  fi

# Aliases
  alias ls='/bin/ls -Ghv'
  alias cernProxy='ssh -D 8080 -Nf cern'
  alias cernProxyDestroy='ps -ef | grep "ssh -D 8080" | grep -v grep | awk '"'"'{print $2}'"'"' | xargs kill'
  alias rarFit='$HOME/rarfit/tmp/rarFit'

# Functions

# LHCb
  export LHCBDOC=svn+ssh://svn.cern.ch/reps/lhcbdocs

# Other
  #test -r /sw/bin/init.sh && . /sw/bin/init.sh
  #alias mail-trends='cd /usr/local/mail-trends; sudo python main.py   --server=imap.gmail.com   --use_ssl   --username=djkarras@gmail.com   --me=djkarras@gmail.com,albert@thenet.uni.cc,apuig@ecm.ub.es,apuignav@cern.ch,albert.puig.navarro@cern.ch --skip_label && open /Applications/Minefield.app /usr/local/mail-trends/out/index.html; cd $HOME'
  #defaults write com.apple.finder _FXShowPosixPathInTitle -bool YES
# Load local config
[[ -f ~/.localrc ]] && source ~/.localrc
[[ -f ~/.functions ]] && source ~/.functions

#eval `ssh-agent`
#ssh-add $HOME/.ssh/id_dsa
#ssh-add -l

